# Generated by Django 4.0.4 on 2022-04-25 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busAgency', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={},
        ),
    ]
