# Generated by Django 4.0.4 on 2022-04-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busAgency', '0003_alter_ticket_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='seat_taken',
        ),
        migrations.AddField(
            model_name='destination',
            name='seat_taken',
            field=models.IntegerField(default=0),
        ),
    ]
