# Generated by Django 4.0.4 on 2022-04-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busAgency', '0004_remove_bus_seat_taken_destination_seat_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='dni',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='dni',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
