# Generated by Django 4.0.4 on 2022-04-27 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busAgency', '0006_driver_is_working'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='duration',
        ),
    ]
